package Indexing.LuceneCustomClasses;

import java.util.Arrays;
import java.util.List;

/**
 * Created by spyridons on 3/17/2017.
 */
public class StopwordLists {

    public static final List<String> stopWordsES = Arrays.asList(
            /*"primer","primera",
            "primero","primeros","bajo","medio","momento","durante",
            "dar","siempre","vez","tiempo",
            ,"trabaja","trabajo","trabajais","trabajamos","trabajan",
            "trabajar","trabajas",
            */
            "considera","consideró","sobre","posible","otro","otra","otras","otros","mas","mejor","cuándo","cuando",
            "a","actualmente","acuerdo","adelante","ademas",
            "además","adrede","afirmó","agregó","ahi",
            "ahora","ahí","al","algo","alguna",
            "algunas","alguno","algunos","algún","alli",
            "allí","alrededor","ambos","ampleamos","antano",
            "antaño","ante","anterior","antes","apenas",
            "aproximadamente","aquel","aquella","aquellas","aquello",
            "aquellos","aqui","aquél","aquélla","aquéllas",
            "aquéllos","aquí","arriba","arribaabajo","aseguró",
            "asi","así","atras","aun","aunque",
            "ayer","añadió","aún","b",
            "bastante","bien","breve","buen","buena",
            "buenas","bueno","buenos","c",
            "casi","cerca","cierta","ciertas","cierto",
            "ciertos","cinco","claro","comentó","como",
            "con","conmigo","conocer","conseguimos","conseguir",
            "consigo","consigue","consiguen",
            "consigues","contigo","contra","cosas","creo",
            "cual","cuales","cualquier","cuanta",
            "cuantas","cuanto","cuantos","cuatro","cuenta",
            "cuál","cuáles","cuánta","cuántas",
            "cuánto","cuántos","cómo","d","da",
            "dado","dan","de",
//            "debajo", 
            "debe", "debería", "deben","debo","debido","decir","dejó",
            "del","delante","demasiado","demás","dentro",
            "deprisa","desde","despacio","despues","después",
            "detras","detrás","dia","dias","dice",
            "dicen","dicho","dieron","diferente","diferentes",
            "dijeron","dijo","dio","donde","dos",
            "día","días","dónde","e",
            "ejemplo","el","ella","ellas","ello",
            "ellos","embargo","empleais","emplean","emplear",
            "empleas","empleo","en","encima","encuentra",
            "enfrente","enseguida","entonces","entre","era",
            "eramos","eran","eras","eres","es",
            "esa","esas","ese","eso","esos",
            "esta","estaba","estaban","estado","estados",
            "estais","estamos","estan","estar","estará",
            "estas","este","esto","estos","estoy",
            "estuvo","está","están","ex","excepto",
            "existe","existen","explicó","expresó","f",
            "fin","final","fue","fuera","fueron",
            "fui","fuimos","g","general","gran",
            "grandes","gueno","h","ha","haber",
            "habia","habla","hablan","habrá","había",
            "habían","hace","haceis","hacemos","hacen",
            "hacer","hacerlo","haces","hacia","haciendo",
            "hago","han","hasta","hay","haya",
            "he","hecho","hemos","hicieron","hizo",
            "horas","hoy","hubo","i","igual",
            "incluso","indicó","informo","informó","intenta",
            "intentais","intentamos","intentan","intentar","intentas",
            "intento","ir","j","junto","k",
            "l","la","lado","largo","las",
            "le","lejos","les","llegó","lleva",
            "llevar","lo","los","luego","lugar",
            "m","mal","manera","manifestó",
            "mayor","me","mediante",
            "mencionó","menos","menudo","mi","mia",
            "mias","mientras","mio","mios","mis",
            "misma","mismas","mismo","mismos","modo",
            "mucha","muchas","mucho","muchos",
            "muy","más","mí","mía","mías",
            "mío","míos","n","nada","nadie","necesito",
            "ni","ninguna","ningunas","ninguno","ningunos",
            "ningún","no","nos","nosotras","nosotros",
            "nuestra","nuestras","nuestro","nuestros","nueva",
            "nuevas","nuevo","nuevos","nunca","o",
            "ocho","os","p","pais","para","parece",
            "parte","partir","pasada","pasado","paìs", "pág",
            "peor","pero","pesar","poca","pocas",
            "poco","pocos","podeis","podemos","poder",
            "podria","podriais","podriamos","podrian","podrias",
            "podrá","podrán","podría","podrías","podrían","poner","por favor",
            "por", "porque","principalmente","pronto","propia",
            "propias","propio","propios","proximo","próximo",
            "próximos","pudo","pueda","puede","pueden",
            "puedo","pues","q","qeu","que",
            "quedó","queremos","quien","quienes","quiere",
            "quiza","quizas","quizá","quizás","quién",
            "quiénes","qué","r","raras","realizado",
            "realizar","realizó","repente","respecto","s",
            "sabe","sabeis","sabemos","saben","saber",
            "sabes","salvo","se","sea","sean",
            "segun","segunda","segundo","según","seis",
            "ser","sera","será","serán","sería",
            "señaló","si","sido","siendo",
            "siete","sigue","siguiente","sin","sino",
            "sois","sola","solamente","solas",
            "solo","solos","somos","son","soy",
            "soyos","su","supuesto","sus","suya",
            "suyas","suyo","sé","sí","sólo",
            "t","tal","tambien","también","tampoco",
            "tan","tanto","tarde", "tendré", "te","temprano",
            "tendrá","tendrán","teneis","tenemos","tener",
            "tenga","tengo","tenido","tenía","tercera",
            "ti","tiene","tienen","toda",
            "todas","todavia","todavía","todo","todos",
            "total","tras","trata",
            "través","tres","tu","tus","tuvo",
            "tuya","tuyas","tuyo","tuyos","tú",
            "u","ultimo","un","una","unas",
            "uno","unos","usa","usais","usamos",
            "usan","usar","usas","uso","usted",
            "ustedes","v","va","vais","valor",
            "vamos","van","varias","varios","vaya",
            "veces","ver","verdad","verdadera","verdadero",
            "vosotras","vosotros","voy","vuestra",
            "vuestras","vuestro","vuestros","w","x",
            "y","ya","yo","z","él",
            "ésa","ésas","ése","ésos","ésta",
            "éstas","éste","éstos","última","últimas",
            "último","últimos",
            "preguntando",
            "sabré",
            "información",
            "gustaría",
            "favor",
            "puedes",
            "explicarme",
            "facilitarme",
            "informarme", "aconsejable", "específico", "oído",
            "pasa", "tardarán", "tendría", "quiero" 
    );

    public static final List<String> stopWordsDE = Arrays.asList(
            "aber","alle","allem","allen","aller","alles","als","also","am","an","ander","andere","anderem",
            "anderen","anderer","anderes","anderm","andern","anderr","anders","auch","auf",
            "aus","bei","bin","bis","bist","da","damit","dann","das","dasselbe","dazu","daß","dein","deine",
            "deinem","deinen","deiner","deines","dem","demselben","den","denn","denselben",
            "der","derer","derselbe","derselben","des","desselben","dessen","dich","die","dies",
            "diese","dieselbe","dieselben","diesem","diesen","dieser","dieses","dir","doch",
            "dort","du","durch","ein","eine","einem","einen","einer","eines","einig","einige","einigem",
            "einigen","einiger","einiges","einmal","er","es","etwas","euch","euer","eure","eurem",
            "euren","eurer","eures","für","gegen","gewesen","hab","habe","haben","hat","hatte","hatten",
            "hier","hin","hinter","ich","ihm","ihn","ihnen","ihr","ihre","ihrem","ihren","ihrer","ihres",
            "im","in","indem","ins","ist","jede","jedem","jeden","jeder","jedes","jene","jenem","jenen",
            "jener","jenes","jetzt","kann","kein","keine","keinem","keinen","keiner","keines",
            "können","könnte","machen","man","manche","manchem","manchen","mancher","manches",
            "mein","meine","meinem","meinen","meiner","meines","mich","mir","mit","muss","musste",
            "nach","nicht","nichts","noch","nun","nur","ob","oder","ohne","sehr","sein","seine","seinem",
            "seinen","seiner","seines","selbst","sich","sie","sind","so","solche","solchem","solchen",
            "solcher","solches","soll","sollte","sondern","sonst","um","und","uns","unse","unsem",
            "unsen","unser","unses","unter","viel","vom","von","vor","war","waren","warst","was","weg",
            "weil","weiter","welche","welchem","welchen","welcher","welches","wenn","werde",
            "werden","wie","wieder","will","wir","wird","wirst","wo","wollen","wollte","während",
            "würde","würden","zu","zum","zur","zwar","zwischen","über",
            "kannst","mehr","information","gerne","sagen","gibt","empfohlen","sollten","hätte","paar","geben" 
    );
}
